env:
  ACTIONS_STEP_DEBUG: true

name: Deploy to EC2

on:
  push:
    paths:
      - 'backend/**'  # Run the workflow only when changes are made to the backend directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build and push Docker image to ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com
          
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest backend/
          
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest
          
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Wait for a few seconds
        run: sleep 2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: SSH into EC2 and restart container with secret environment variable
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Debugging: Inside SSH script"
            docker stop karenslist-app
            docker rm karenslist-app
            docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest
            docker run -d -p 8000:8000 --name karenslist-app \
              -e URL_DATABASE="${{ secrets.URL_DATABASE }}" \
              ${{ secrets.ECR_REPOSITORY_URI }}:latest
            echo "Debugging: After running Docker commands"

